apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: demo-123
build:
  artifacts:
    - image: piomin/demo-123
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}