apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-123
spec:
  selector:
    matchLabels:
      app: demo-123
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: demo-123
    spec:
      containers:
        - name: demo-123
          image: piomin/demo-123
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-123
spec:
  type: NodePort
  selector:
    app: demo-123
  ports:
    - port: 8080
      nodePort: 30000